import type { CampaignFormData, EnrichedData } from '../types';

interface DiffRow {
  field: string;
  original: string | undefined;
  enriched: string;
  badge: 'generated' | 'transformed' | 'unchanged';
}

function buildDiffRows(form: CampaignFormData, enriched: EnrichedData): DiffRow[] {
  const rows: DiffRow[] = [];

  rows.push({
    field: 'Program Name',
    original: form.name,
    enriched: enriched.programName,
    badge: 'transformed',
  });
  rows.push({
    field: 'Template ID',
    original: undefined,
    enriched: String(enriched.templateId),
    badge: 'generated',
  });
  rows.push({
    field: 'Folder ID',
    original: undefined,
    enriched: String(enriched.folderId),
    badge: 'generated',
  });
  rows.push({
    field: 'Email Subject',
    original: form.emailSubject || undefined,
    enriched: enriched.emailSubject,
    badge: form.emailSubject ? 'unchanged' : 'generated',
  });
  rows.push({
    field: 'Region',
    original: form.region || undefined,
    enriched: enriched.region,
    badge: form.region ? 'unchanged' : 'generated',
  });
  rows.push({
    field: 'UTM Source',
    original: undefined,
    enriched: enriched.utmSource,
    badge: 'generated',
  });
  rows.push({
    field: 'UTM Medium',
    original: undefined,
    enriched: enriched.utmMedium,
    badge: 'generated',
  });
  rows.push({
    field: 'UTM Campaign',
    original: undefined,
    enriched: enriched.utmCampaign,
    badge: 'generated',
  });
  rows.push({
    field: 'SFDC Status',
    original: undefined,
    enriched: enriched.sfdcStatus,
    badge: 'generated',
  });
  rows.push({
    field: 'SFDC IsActive',
    original: undefined,
    enriched: String(enriched.sfdcIsActive),
    badge: 'generated',
  });
  rows.push({
    field: 'Marketo Tokens',
    original: undefined,
    enriched: `${enriched.marketoTokens.length} tokens`,
    badge: 'generated',
  });

  return rows;
}

const badgeStyles = {
  generated: 'bg-emerald-50 text-emerald-700 border-emerald-200',
  transformed: 'bg-blue-50 text-blue-700 border-blue-200',
  unchanged: 'bg-gray-50 text-gray-500 border-gray-200',
};

export function EnrichmentDiff({
  formData,
  enrichedData,
}: {
  formData: CampaignFormData;
  enrichedData: EnrichedData;
}) {
  const rows = buildDiffRows(formData, enrichedData);

  return (
    <div className="animate-fade-in">
      <div className="flex items-center gap-4 mb-4">
        <span className="flex items-center gap-1.5 text-xs">
          <span className="w-2 h-2 rounded-full bg-emerald-500" />
          Generated by Claude
        </span>
        <span className="flex items-center gap-1.5 text-xs">
          <span className="w-2 h-2 rounded-full bg-blue-500" />
          Transformed by Claude
        </span>
        <span className="flex items-center gap-1.5 text-xs">
          <span className="w-2 h-2 rounded-full bg-gray-400" />
          Unchanged
        </span>
      </div>

      <div className="border border-gray-200 rounded-lg overflow-x-auto">
        <table className="w-full min-w-[700px]">
          <thead>
            <tr className="bg-gray-50 border-b border-gray-200 text-xs font-medium text-gray-500 uppercase tracking-wider">
              <th className="text-left px-4 py-2 w-[130px]">Field</th>
              <th className="text-left px-4 py-2">Form Input</th>
              <th className="text-left px-4 py-2">Claude Output</th>
              <th className="text-left px-4 py-2 w-[100px]">Status</th>
            </tr>
          </thead>
          <tbody>
            {rows.map((row) => (
              <tr key={row.field} className="border-b border-gray-100 last:border-b-0 text-sm">
                <td className="px-4 py-2.5 font-medium text-gray-700">{row.field}</td>
                <td className="px-4 py-2.5 font-mono text-xs text-gray-400">
                  {row.original ?? <span className="italic">—</span>}
                </td>
                <td className="px-4 py-2.5 font-mono text-xs text-gray-900">{row.enriched}</td>
                <td className="px-4 py-2.5">
                  <span
                    className={`inline-flex px-2 py-0.5 rounded-full text-[10px] font-medium border whitespace-nowrap ${badgeStyles[row.badge]}`}
                  >
                    {row.badge}
                  </span>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {enrichedData.warnings.length > 0 && (
        <div className="mt-3 space-y-2">
          {enrichedData.warnings.map((w, i) => (
            <div
              key={i}
              className="bg-amber-50 border border-amber-200 rounded-lg px-4 py-2 text-sm text-amber-800 flex items-center gap-2"
            >
              <span className="text-amber-500 font-bold">!</span>
              {w}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
